on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *

name: Upload Apps

jobs:
  build:
    name: Upload Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Compile App
        run: |
          export TESTFAIRY_KEYSTORE_PASSWORD=${{ secrets.TESTFAIRY_KEYSTORE_PASSWORD }}
          echo ${{ secrets.TESTFAIRY_KEYSTORE_BASE64 }} | base64 -d > testfairy.keystore
          printf "\norg.gradle.daemon=false" >> gradle.properties

          ./gradlew TestFairyApp:assembleRelease

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./TestFairyApp/build/outputs/apk/mobile/release/TestFairyApp-mobile-release.apk
            ./TestFairyApp/build/outputs/apk/tv/release/TestFairyApp-tv-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}