name: Publish Release

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.1

